[package]
name = "canvas"
version = "0.1.0"
edition = "2021"

[dependencies]
# Use simple winit for now to get started
winit = "0.29"
softbuffer = "0.4"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }